### ISSUE TITLE
[Feature Request] Add support for non-cubic 3D models.

### ISSUE THREAD

**Issue by Titus-Armillius** [Leviathan143/betterbeginnings-MODIFIED#36]
**Description:**
Due to the coding of the kiln block, models which do not have a cubic, flat-faced design cause adjacent block faces to render invisible. Kitsu over at the Primal discord who is a developer said that the fix for this is a minor code change. 

http://i.imgur.com/KiarWjC.jpg (picture of effect)

**Steps to reproduce:**
Replace kiln model with non-cubic 3D model.

**Version Info(Exact versions only):**
BetterBeginnings: lastest 1.10.2 version.

Forge: lastest 1.10.2 forge

**Comment by Leviathan143** [comment]
The issue here is occlusion culling(not rendering stuff that can't be seen). MC's occlusion culling is very simple, if there's a block that says it's an opaque 1m3 cube touching a face of another block, that face isn't rendered. The purpose of this is to reduce load on the GPU. 

The issue you're having will occur with any block that is usually an opaque 1m3 cube, whether it is mod-added, or vanilla. I could fix this in BB by disabling occlusion culling, but I don't think it's worth it just for non-cubic model support. It's not that there would be a major performance hit, unless you make a wall of kilns. It's that I honestly can't be bothered to disable occlusion culling for all current and future blocks, just for non-cubic models, especially since vanilla and every other mod don't.
